### ISSUE TITLE
Add Swagger UI

### ISSUE THREAD

**Issue by Nikhil-Sarwara** [EventBurst/shiny-barnacle#19]
Add swagger ui for api routes

- [x] Completed

![image](https://github.com/EventBurst/shiny-barnacle/assets/117506262/9b365132-8778-44c5-aef2-5b7fc7a1da8f)

**Comment by Nikhil-Sarwara** [comment]
Brother I have created another branch for so we will add swagger in new branch.

**Comment by Developer-vansh** [comment]
Ok brother
